version: "3"

services:
  # Laravel Backend
  laravel:
    build:
      context: ./laravel
    container_name: laravel_app
    volumes:
      - ./laravel:/app/laravel
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    networks:
      - laravel

  # React Frontend
  react:
    build:
      context: ./react-app
    container_name: react_app
    volumes:
      - ./react-app:/app/react
    ports:
      - "3000:3000"
    depends_on:
      - laravel
    networks:
      - laravel

  # phpMyAdmin service
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_ARBITARY: 1
      PMA_HOST: mysql
      PMA_USER: root
      PMA_PASSWORD: password
    ports:
      - "8090:80"
    depends_on:
      - mysql
    networks:
      - laravel

  # MySQL Database
  mysql:
    image: mysql:5.7.44
    container_name: laravel_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password123
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_password
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    external: true
